import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import dynamic from "next/dynamic";
// import { AppWrapper } from "./context"; // must use "use client" when using this


dynamic(() => import('bootstrap/dist/js/bootstrap.js'), {
  ssr: false
})



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "My page title",
    description: "This is my description",
    url: "mywebsite.com",
    siteName: "Codewithguillaume",
    images: [
      {
        url: '/mywebsite.png',
        width: 1260,
        height: 800,
      },
      {
        url: '/mywebsite.png',
        width: 1260,
        height: 800,
      }
    ],
    locale: "en-EN",
    
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AppWrapper> */}
          {children}
        {/* </AppWrapper> */}
      </body>

    </html>
  );
}
