services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - 8000:3000
    volumes:
      - .:/app
      - /app/node_modules # prevents folder from being copied into docker container
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ambassador 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql
    ports:
     - 54322:5432
  redis:
    image: redis
    ports:
      - 6379:6379
 